[env:pico]
platform = raspberrypi
board = pico
framework = arduino

monitor_speed = 115200
monitor_port = COM7

lib_extra_dirs = ../../lib
lib_deps =
  adafruit/Adafruit GFX Library

extra_scripts = post:../../copy_uf2.py
